# Generated by Django 6.0 on 2026-02-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0006_alter_mitarbeiter_options_and_more'),
        ('traeger', '0007_remove_stelle_traeger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innenauftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=50, unique=True, verbose_name='Innenauftrag')),
                ('bezeichnung', models.CharField(blank=True, max_length=200)),
                ('aktiv', models.BooleanField(default=True)),
                ('bemerkung', models.TextField(blank=True)),
                ('angelegt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('mitarbeiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innenauftraege', to='personal.mitarbeiter')),
                ('stelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innenauftraege', to='traeger.stelle')),
            ],
            options={
                'ordering': ['nummer'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stelle__isnull', False), ('mitarbeiter__isnull', False), _negated=True), name='innenauftrag_not_both_stelle_and_mitarbeiter'), models.UniqueConstraint(condition=models.Q(('stelle__isnull', False)), fields=('stelle',), name='innenauftrag_unique_stelle'), models.UniqueConstraint(condition=models.Q(('mitarbeiter__isnull', False)), fields=('mitarbeiter',), name='innenauftrag_unique_mitarbeiter')],
            },
        ),
    ]
