# Generated by Django 6.0 on 2026-02-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einsatz', '0004_einsatz_abrechnung'),
        ('mbw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='innenauftrag',
            name='innenauftrag_not_both_stelle_and_mitarbeiter',
        ),
        migrations.RemoveConstraint(
            model_name='innenauftrag',
            name='innenauftrag_unique_stelle',
        ),
        migrations.RemoveConstraint(
            model_name='innenauftrag',
            name='innenauftrag_unique_mitarbeiter',
        ),
        migrations.AddField(
            model_name='innenauftrag',
            name='andock_art',
            field=models.CharField(blank=True, choices=[('stelle', 'an Stelle'), ('person', 'an Person')], max_length=20),
        ),
        migrations.AddField(
            model_name='innenauftrag',
            name='einsatz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innenauftrag', to='einsatz.einsatz'),
        ),
        migrations.RemoveField(
            model_name='innenauftrag',
            name='mitarbeiter',
        ),
        migrations.RemoveField(
            model_name='innenauftrag',
            name='stelle',
        ),
    ]
