# Generated by Django 6.0 on 2026-02-13 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einsatz', '0004_einsatz_abrechnung'),
        ('mbw', '0002_remove_innenauftrag_innenauftrag_not_both_stelle_and_mitarbeiter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartalsabrechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveSmallIntegerField()),
                ('quartal', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('art', models.CharField(choices=[('abschlag', 'Abschlagszahlung'), ('spitze', 'Spitzabrechnung')], editable=False, max_length=20)),
                ('verbucht_am', models.DateField(default=django.utils.timezone.localdate)),
                ('bemerkung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartalsabrechnungen', to='einsatz.einsatz')),
            ],
            options={
                'ordering': ['-jahr', 'quartal', 'einsatz_id'],
                'constraints': [models.UniqueConstraint(fields=('einsatz', 'jahr', 'quartal'), name='unique_quartalsabrechnung_per_einsatz_jahr_quartal')],
            },
        ),
    ]
