# Generated by Django 6.0 on 2026-02-25 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einsatz', '0004_einsatz_abrechnung'),
        ('mbw', '0003_quartalsabrechnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakturierungsvorgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveSmallIntegerField()),
                ('besoldung_gesamt', models.DecimalField(blank=True, decimal_places=2, help_text='Aufgearbeitete Besoldungssumme des Jahres.', max_digits=12, null=True)),
                ('sap_auftragsnummer', models.CharField(blank=True, max_length=100)),
                ('sap_erfasst_am', models.DateField(blank=True, null=True)),
                ('kasse_uebergeben_am', models.DateField(blank=True, null=True)),
                ('rechnungsnummer', models.CharField(blank=True, max_length=100)),
                ('rechnung_pdf', models.FileField(blank=True, null=True, upload_to='mbw/rechnungen/')),
                ('versandart', models.CharField(blank=True, choices=[('email', 'E-Mail'), ('post', 'Post')], max_length=20)),
                ('versandt_am', models.DateField(blank=True, null=True)),
                ('debitor_status', models.CharField(choices=[('offen', 'Offen'), ('teilweise', 'Teilweise ausgeglichen'), ('ausgeglichen', 'Ausgeglichen')], default='offen', max_length=20)),
                ('debitor_geprueft_am', models.DateField(blank=True, null=True)),
                ('bemerkung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakturierungsvorgaenge', to='einsatz.einsatz')),
            ],
            options={
                'ordering': ['-jahr', 'einsatz_id'],
                'constraints': [models.UniqueConstraint(fields=('einsatz', 'jahr'), name='unique_fakturierung_pro_einsatz_und_jahr')],
            },
        ),
    ]
