# Generated by Django 6.0 on 2026-07-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbw', '0004_fakturierungsvorgang'),
        ('traeger', '0008_alter_einrichtung_einrichtungs_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoldungstabelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gueltig_ab', models.DateField(unique=True, verbose_name='Gültig ab')),
                ('erhoehung_prozent', models.DecimalField(blank=True, decimal_places=2, help_text='Erhöhung gegenüber der Vorgängertabelle in Prozent (informativ)', max_digits=5, null=True, verbose_name='Erhöhung %')),
                ('bemerkung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Besoldungstabelle',
                'verbose_name_plural': 'Besoldungstabellen',
                'ordering': ['-gueltig_ab'],
            },
        ),
        migrations.CreateModel(
            name='Familienzuschlagtabelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gueltig_ab', models.DateField(unique=True, verbose_name='Gültig ab')),
                ('erhoehung_prozent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Erhöhung %')),
                ('bemerkung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Familienzuschlagtabelle',
                'verbose_name_plural': 'Familienzuschlagtabellen',
                'ordering': ['-gueltig_ab'],
            },
        ),
        migrations.AddField(
            model_name='innenauftrag',
            name='kostenstelle',
            field=models.CharField(blank=True, db_index=True, help_text='SAP-Kostenstelle, auf der der Auftrag bebucht wird (z. B. 3-0312P033)', max_length=30, verbose_name='Kostenstelle'),
        ),
        migrations.CreateModel(
            name='Beihilfesatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveSmallIntegerField(verbose_name='Jahr')),
                ('tarif', models.CharField(choices=[('814', 'Tarif 814 (Pauschalbeitrag)'), ('830', 'Tarif 830 (altersabhängig)')], max_length=5)),
                ('kategorie', models.CharField(choices=[('erwachsen', 'Erwachsene'), ('kind', 'Kinder')], max_length=10)),
                ('alter_bis', models.PositiveSmallIntegerField(blank=True, help_text='Obergrenze der Altersgruppe einschließlich; leer = keine Obergrenze', null=True, verbose_name='Alter bis')),
                ('satz', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monatsbeitrag')),
            ],
            options={
                'verbose_name': 'Beihilfesatz',
                'verbose_name_plural': 'Beihilfesätze',
                'ordering': ['-jahr', 'tarif', 'kategorie', 'alter_bis'],
                'constraints': [models.UniqueConstraint(fields=('jahr', 'tarif', 'kategorie', 'alter_bis'), name='unique_beihilfesatz')],
            },
        ),
        migrations.CreateModel(
            name='Debitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_nummer', models.CharField(blank=True, db_index=True, help_text='Debitorennummer im SAP S/4HANA (z. B. 1900032335)', max_length=20, verbose_name='SAP-Debitorennummer')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name2', models.CharField(blank=True, max_length=200, verbose_name='Namenszusatz')),
                ('anschriftperson', models.CharField(blank=True, help_text='z. B. „z. Hd. Frau Mustermann“ – erscheint im Rechnungstext', max_length=200, verbose_name='Anschriftperson')),
                ('strasse', models.CharField(blank=True, max_length=150, verbose_name='Straße')),
                ('plz', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='E-Mail')),
                ('versandweg', models.CharField(blank=True, choices=[('email', 'E-Mail'), ('post', 'Post')], max_length=10, verbose_name='Versandweg')),
                ('aktiv', models.BooleanField(default=True)),
                ('bemerkung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('traeger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debitoren', to='traeger.traeger', verbose_name='Träger')),
            ],
            options={
                'verbose_name': 'Debitor',
                'verbose_name_plural': 'Debitoren',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='innenauftrag',
            name='debitor',
            field=models.ForeignKey(blank=True, help_text='Erstattungspflichtiger Rechnungsempfänger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innenauftraege', to='mbw.debitor', verbose_name='Debitor'),
        ),
        migrations.CreateModel(
            name='Mietenstufe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('gemeinde', 'Gemeinde'), ('kreis', 'Landkreis')], max_length=10)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('stufe', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII')], max_length=3, verbose_name='Mietenstufe')),
            ],
            options={
                'verbose_name': 'Mietenstufe',
                'verbose_name_plural': 'Mietenstufen',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('art', 'name'), name='unique_mietenstufe')],
            },
        ),
        migrations.CreateModel(
            name='Zulagensatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('struktur', 'Strukturzulage (A 9 – A 13)'), ('amt', 'Amtszulage'), ('heim', 'Heimzulage'), ('heimleiter', 'Heimleiterzulage')], max_length=20)),
                ('variante', models.CharField(blank=True, help_text='z. B. „A9 I“ bei Amtszulagen; leer bei Struktur-/Heimzulage', max_length=20)),
                ('gueltig_ab', models.DateField(verbose_name='Gültig ab')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monatsbetrag')),
                ('bemerkung', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Zulagensatz',
                'verbose_name_plural': 'Zulagensätze',
                'ordering': ['art', 'variante', '-gueltig_ab'],
                'constraints': [models.UniqueConstraint(fields=('art', 'variante', 'gueltig_ab'), name='unique_zulagensatz')],
            },
        ),
        migrations.CreateModel(
            name='Besoldungsbetrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppe', models.CharField(choices=[('A3', 'A 3'), ('A4', 'A 4'), ('A5', 'A 5'), ('A6', 'A 6'), ('A7', 'A 7'), ('A8', 'A 8'), ('A9', 'A 9'), ('A10', 'A 10'), ('A11', 'A 11'), ('A12', 'A 12'), ('A13', 'A 13'), ('A14', 'A 14'), ('A15', 'A 15'), ('A16', 'A 16')], max_length=5, verbose_name='Besoldungsgruppe')),
                ('stufe', models.PositiveSmallIntegerField(verbose_name='Stufe')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Monatsbetrag')),
                ('tabelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betraege', to='mbw.besoldungstabelle')),
            ],
            options={
                'verbose_name': 'Besoldungsbetrag',
                'verbose_name_plural': 'Besoldungsbeträge',
                'ordering': ['gruppe', 'stufe'],
                'constraints': [models.UniqueConstraint(fields=('tabelle', 'gruppe', 'stufe'), name='unique_besoldungsbetrag_pro_tabelle_gruppe_stufe')],
            },
        ),
        migrations.CreateModel(
            name='Familienzuschlagzeile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ortsklasse', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII')], max_length=3)),
                ('stufe_l', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stufe L')),
                ('stufe_v', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stufe V')),
                ('stufe_1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stufe 1')),
                ('stufe_2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stufe 2')),
                ('kind_3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='zzgl. 3. Kind')),
                ('kind_weitere', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='zzgl. je weiterem Kind')),
                ('tabelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeilen', to='mbw.familienzuschlagtabelle')),
            ],
            options={
                'verbose_name': 'Familienzuschlag-Zeile',
                'verbose_name_plural': 'Familienzuschlag-Zeilen',
                'ordering': ['ortsklasse'],
                'constraints': [models.UniqueConstraint(fields=('tabelle', 'ortsklasse'), name='unique_fz_zeile_pro_tabelle_ortsklasse')],
            },
        ),
        migrations.CreateModel(
            name='FZKinderErhoehung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ortsklasse', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII')], max_length=3)),
                ('gruppe', models.CharField(choices=[('A3', 'A 3'), ('A4', 'A 4'), ('A5', 'A 5'), ('A6', 'A 6'), ('A7', 'A 7'), ('A8', 'A 8'), ('A9', 'A 9'), ('A10', 'A 10'), ('A11', 'A 11'), ('A12', 'A 12'), ('A13', 'A 13'), ('A14', 'A 14'), ('A15', 'A 15'), ('A16', 'A 16')], max_length=5, verbose_name='Besoldungsgruppe')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Erhöhung je Kind')),
                ('tabelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinder_erhoehungen', to='mbw.familienzuschlagtabelle')),
            ],
            options={
                'verbose_name': 'FZ-Kindererhöhung (A8–A10)',
                'verbose_name_plural': 'FZ-Kindererhöhungen (A8–A10)',
                'ordering': ['gruppe', 'ortsklasse'],
                'constraints': [models.UniqueConstraint(fields=('tabelle', 'ortsklasse', 'gruppe'), name='unique_fz_kindererhoehung')],
            },
        ),
    ]
