# Generated by Django 6.0 on 2026-07-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbw', '0005_besoldungstabelle_familienzuschlagtabelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='abschlag_quartal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vorschlag: Hochrechnung ÷ 4, abgerundet auf volle 500 €', max_digits=12, null=True, verbose_name='Abschlag je Quartal'),
        ),
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='debitor',
            field=models.ForeignKey(blank=True, help_text='Rechnungsempfänger; Vorbelegung kommt vom Innenauftrag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jahresakten', to='mbw.debitor', verbose_name='Debitor'),
        ),
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='hochrechnung_gesamt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Jahres-Hochrechnung'),
        ),
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='kalkulation',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='kalkuliert_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quartalsabrechnung',
            name='betrag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Abschlags- bzw. Rechnungsbetrag des Quartals', max_digits=12, null=True, verbose_name='Betrag'),
        ),
    ]
