# Generated by Django 6.0 on 2026-07-10 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbw', '0006_fakturierungsvorgang_abschlag_quartal_and_more'),
        ('personal', '0007_mitarbeiter_beihilfe_art_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='pos_beihilfe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Position 10171 – Beihilfepauschale/KV-Zuschuss'),
        ),
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='pos_bezuege',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Position 10159 – Bezüge DiakonInnen'),
        ),
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='pos_umlage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Position 10167 – Umlage Versorgungsfonds'),
        ),
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='spitze_berechnet_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='spitze_rest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PK gesamt abzüglich gebuchter Abschlagszahlungen', max_digits=12, null=True, verbose_name='Restbetrag Schlussrechnung'),
        ),
        migrations.CreateModel(
            name='PersonalkostenImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateiname', models.CharField(max_length=255)),
                ('jahr', models.PositiveSmallIntegerField(help_text='Aus den Für-Perioden der Datei abgeleitet', verbose_name='Abrechnungsjahr')),
                ('bemerkung', models.TextField(blank=True)),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('hochgeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pk_importe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personalkosten-Import',
                'verbose_name_plural': 'Personalkosten-Importe',
                'ordering': ['-hochgeladen_am'],
            },
        ),
        migrations.AddField(
            model_name='fakturierungsvorgang',
            name='pk_import',
            field=models.ForeignKey(blank=True, help_text='SAP-Auswertung, aus der die Ist-Positionen stammen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jahresakten', to='mbw.personalkostenimport', verbose_name='Personalkosten-Import'),
        ),
        migrations.CreateModel(
            name='PersonalkostenZeile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lfd_nr', models.PositiveIntegerField(verbose_name='lfd. Nr.')),
                ('personalnummer', models.CharField(db_index=True, max_length=10)),
                ('nachname', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('lbe', models.CharField(blank=True, max_length=20, verbose_name='L B E')),
                ('kostenstelle', models.CharField(blank=True, max_length=30)),
                ('auftrag_nummer', models.CharField(db_index=True, max_length=50, verbose_name='Auftrag')),
                ('hauptbuchkonto', models.CharField(db_index=True, max_length=10, verbose_name='Hauptb')),
                ('lohnart', models.CharField(max_length=10, verbose_name='LArt')),
                ('lohnart_text', models.CharField(blank=True, max_length=100, verbose_name='Lohnart-Langtext')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waehrung', models.CharField(default='EUR', max_length=5)),
                ('text', models.CharField(blank=True, max_length=50)),
                ('fuer_periode', models.CharField(blank=True, max_length=6, verbose_name='Fürper.')),
                ('in_periode', models.CharField(blank=True, max_length=6, verbose_name='Inper.')),
                ('import_lauf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeilen', to='mbw.personalkostenimport')),
                ('innenauftrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalkosten_zeilen', to='mbw.innenauftrag')),
                ('mitarbeiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalkosten_zeilen', to='personal.mitarbeiter')),
                ('storno_partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storno_gegenstueck', to='mbw.personalkostenzeile')),
            ],
            options={
                'verbose_name': 'Personalkosten-Zeile',
                'verbose_name_plural': 'Personalkosten-Zeilen',
                'ordering': ['lfd_nr'],
                'constraints': [models.UniqueConstraint(fields=('import_lauf', 'lfd_nr'), name='unique_pk_zeile_lfd_nr')],
            },
        ),
    ]
