# Generated by Django 6.0 on 2026-07-21 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbw', '0007_fakturierungsvorgang_pos_beihilfe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zahlungseingang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.localdate, verbose_name='Zahlungsdatum')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag')),
                ('bemerkung', models.CharField(blank=True, max_length=200, verbose_name='Bemerkung')),
                ('erfasst_am', models.DateTimeField(auto_now_add=True)),
                ('erfasst_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vorgang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zahlungseingaenge', to='mbw.fakturierungsvorgang', verbose_name='Jahresakte')),
            ],
            options={
                'verbose_name': 'Zahlungseingang',
                'verbose_name_plural': 'Zahlungseingänge',
                'ordering': ['datum', 'id'],
            },
        ),
    ]
