# Generated by Django 6.0 on 2026-01-22 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansprechpartner', '0001_initial'),
        ('beurteilung', '0002_evaluation_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationrequest',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansprechpartner.ansprechpartner'),
        ),
    ]
