from django.urls import path

from .views import (
    abrechnungsliste,
    besoldungstabelle_detail,
    besoldungstabelle_erhoehen,
    besoldungstabelle_neu,
    cockpit,
    cockpit_export,
    debitor_create,
    debitor_update,
    debitorenliste,
    fakturierung_bearbeiten,
    fakturierungsliste,
    fz_tabelle_detail,
    fz_tabelle_erhoehen,
    fz_tabelle_neu,
    aktive_einsaetze,
    jahresakte,
    jahresakte_kalkulieren,
    jahresakte_spitze,
    pk_debitor_mappe,
    pk_fall_excel,
    pk_import_detail,
    pk_import_liste,
    pk_import_loeschen,
    innenauftrag_create,
    innenauftrag_freigeben,
    innenauftrag_update,
    innenauftrag_zuweisen,
    innenauftraege,
    mbw,
    mietenstufen,
    quartalsabrechnung_buchen,
    quartalsuebersicht,
    stammdaten,
    zahlungseingang_anlegen,
    zahlungseingang_loeschen,
)

urlpatterns = [
    path("jahresakte/<int:pk>/<int:jahr>/", jahresakte, name="jahresakte"),
    path("jahresakte/<int:pk>/<int:jahr>/kalkulieren/", jahresakte_kalkulieren, name="jahresakte_kalkulieren"),
    path("jahresakte/<int:pk>/<int:jahr>/spitze/", jahresakte_spitze, name="jahresakte_spitze"),
    path("jahresakte/<int:pk>/<int:jahr>/zahlung/", zahlungseingang_anlegen, name="zahlungseingang_anlegen"),
    path("zahlung/<int:pk>/loeschen/", zahlungseingang_loeschen, name="zahlungseingang_loeschen"),
    path("cockpit/", cockpit, name="cockpit"),
    path("cockpit/export/", cockpit_export, name="cockpit_export"),
    path("pk-import/", pk_import_liste, name="pk_import_liste"),
    path("pk-import/<int:pk>/", pk_import_detail, name="pk_import_detail"),
    path("pk-import/<int:pk>/loeschen/", pk_import_loeschen, name="pk_import_loeschen"),
    path("pk-import/<int:pk>/fall/<str:personalnummer>/<str:auftrag>/excel/", pk_fall_excel, name="pk_fall_excel"),
    path("pk-import/<int:pk>/debitor/<int:debitor_pk>/mappe/", pk_debitor_mappe, name="pk_debitor_mappe"),
    path("stammdaten/", stammdaten, name="mbw_stammdaten"),
    path("stammdaten/besoldung/neu/", besoldungstabelle_neu, name="besoldungstabelle_neu"),
    path("stammdaten/besoldung/<int:pk>/", besoldungstabelle_detail, name="besoldungstabelle_detail"),
    path("stammdaten/besoldung/erhoehen/", besoldungstabelle_erhoehen, name="besoldungstabelle_erhoehen"),
    path("stammdaten/fz/neu/", fz_tabelle_neu, name="fz_tabelle_neu"),
    path("stammdaten/fz/<int:pk>/", fz_tabelle_detail, name="fz_tabelle_detail"),
    path("stammdaten/fz/erhoehen/", fz_tabelle_erhoehen, name="fz_tabelle_erhoehen"),
    path("stammdaten/debitoren/", debitorenliste, name="debitorenliste"),
    path("stammdaten/debitoren/neu/", debitor_create, name="debitor_create"),
    path("stammdaten/debitoren/<int:pk>/bearbeiten/", debitor_update, name="debitor_update"),
    path("stammdaten/mietenstufen/", mietenstufen, name="mietenstufen"),
    path("", mbw, name="mbw"),
    path("aktive-einsaetze/", aktive_einsaetze, name="aktive_einsaetze"),
    path("abrechnung/", abrechnungsliste, name="abrechnungsliste"),
    path("innenauftraege/", innenauftraege, name="innenauftraege"),
    path("innenauftraege/neu/", innenauftrag_create, name="innenauftrag_create"),
    path("innenauftraege/<int:pk>/bearbeiten/", innenauftrag_update, name="innenauftrag_update"),
    path("innenauftraege/<int:pk>/freigeben/", innenauftrag_freigeben, name="innenauftrag_freigeben"),
    path("abrechnung/<int:pk>/innenauftrag-zuweisen/", innenauftrag_zuweisen, name="innenauftrag_zuweisen"),
    path("quartale/", quartalsuebersicht, name="quartalsuebersicht"),
    path("quartale/<int:pk>/buchen/", quartalsabrechnung_buchen, name="quartalsabrechnung_buchen"),
    path("fakturierung/", fakturierungsliste, name="fakturierungsliste"),
    path("fakturierung/<int:pk>/bearbeiten/", fakturierung_bearbeiten, name="fakturierung_bearbeiten"),
]
