# Generated by Django 6.0 on 2026-01-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ansprechpartner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('art', models.CharField(choices=[('dw', 'Diakonischer Träger'), ('lk', 'Landeskirchenamt'), ('db', 'Dekanat'), ('kg', 'Kirchengemeinde'), ('kr', 'Krankenhäuser'), ('sn', 'Sonstiger Träger')], max_length=2, verbose_name='Art')),
                ('traeger_id', models.CharField(blank=True, max_length=50, verbose_name='Träger-Id')),
                ('strasse', models.CharField(blank=True, max_length=100, verbose_name='Straße')),
                ('plz', models.CharField(blank=True, max_length=5, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('versorgungsumlage', models.DecimalField(choices=[('0.00', 'keine'), ('0.40', '40 %'), ('0.68', '68 %')], decimal_places=2, default='0.40', max_digits=4, verbose_name='Versorgungsumlage')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('haupt_ansprechpartner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haupt_traeger', to='ansprechpartner.ansprechpartner')),
            ],
            options={
                'verbose_name': 'Träger',
                'verbose_name_plural': 'Träger',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stellen_id', models.CharField(blank=True, max_length=50, verbose_name='Stellen-Id')),
                ('strasse', models.CharField(blank=True, max_length=100, verbose_name='Straße')),
                ('plz', models.CharField(blank=True, max_length=5, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('aktiv', models.BooleanField(default=True)),
                ('ansprechpartner', models.ManyToManyField(blank=True, related_name='stellen', to='ansprechpartner.ansprechpartner')),
                ('traeger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stellen', to='traeger.traeger')),
            ],
        ),
    ]
