# Generated by Django 6.0 on 2026-01-18 15:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traeger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stelle',
            options={'ordering': ['name'], 'verbose_name': 'Stellen', 'verbose_name_plural': 'Stellen'},
        ),
        migrations.AlterField(
            model_name='traeger',
            name='art',
            field=models.CharField(choices=[('dw', 'Diakonischer Träger'), ('lk', 'Landeskirchenamt'), ('db', 'Dekanat'), ('kg', 'Kirchengemeinde'), ('kr', 'Krankenhäuser'), ('sn', 'Sonstiger Träger')], db_index=True, max_length=2, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='traeger',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='traeger',
            name='traeger_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Träger-Id'),
        ),
        migrations.AlterField(
            model_name='traeger',
            name='versorgungsumlage',
            field=models.DecimalField(choices=[('0.00', 'keine'), ('0.40', '40 %'), ('0.68', '68 %')], decimal_places=2, default=Decimal('0.40'), max_digits=4, verbose_name='Versorgungsumlage'),
        ),
    ]
