# Generated by Django 6.0 on 2026-01-18 23:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traeger', '0002_alter_stelle_options_alter_traeger_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traeger',
            name='versorgungsumlage',
            field=models.DecimalField(choices=[(Decimal('0.00'), 'keine'), (Decimal('0.40'), '40 %'), (Decimal('0.68'), '68 %')], decimal_places=2, default=Decimal('0.40'), max_digits=4, verbose_name='Versorgungsumlage'),
        ),
    ]
