# Generated by Django 6.0 on 2026-01-19 20:22

from decimal import Decimal
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traeger', '0003_alter_traeger_versorgungsumlage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stelle',
            name='bemerkung',
            field=models.TextField(blank=True, verbose_name='Bemerkung'),
        ),
        migrations.AddField(
            model_name='stelle',
            name='erstellt_am',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stelle',
            name='geaendert_am',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stelle',
            name='versorgungsumlage',
            field=models.DecimalField(choices=[(Decimal('0.00'), 'keine'), (Decimal('0.40'), '40 %'), (Decimal('0.68'), '68 %')], decimal_places=2, default=Decimal('0.40'), max_digits=4, verbose_name='Versorgungsumlage'),
        ),
    ]
