# Generated by Django 6.0 on 2026-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traeger', '0004_stelle_bemerkung_stelle_erstellt_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stelle',
            name='position',
            field=models.CharField(blank=True, help_text='Was für eine Position hat die Stelle', max_length=250, verbose_name='Position'),
        ),
    ]
