# Generated by Django 6.0 on 2026-01-21 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansprechpartner', '0001_initial'),
        ('traeger', '0005_stelle_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stelle',
            name='ansprechpartner',
        ),
        migrations.AddField(
            model_name='stelle',
            name='ansprechpartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stellen', to='ansprechpartner.ansprechpartner'),
        ),
    ]
