# Generated by Django 6.0 on 2026-01-25 14:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansprechpartner', '0001_initial'),
        ('traeger', '0006_remove_stelle_ansprechpartner_stelle_ansprechpartner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stelle',
            name='traeger',
        ),
        migrations.RemoveField(
            model_name='stelle',
            name='versorgungsumlage',
        ),
        migrations.RemoveField(
            model_name='traeger',
            name='versorgungsumlage',
        ),
        migrations.AlterField(
            model_name='traeger',
            name='art',
            field=models.CharField(choices=[('dw', 'Diakonischer Träger'), ('lk', 'Landeskirchenamt'), ('db', 'Dekanat'), ('kr', 'Krankenhäuser'), ('sn', 'Sonstiger Träger')], db_index=True, max_length=2, verbose_name='Art'),
        ),
        migrations.CreateModel(
            name='Einrichtung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('einrichtung_art', models.CharField(blank=True, choices=[('dw', 'Diakonische Einrichtung'), ('ab', 'Abteilung'), ('kg', 'Kirchengemeinde'), ('kr', 'Krankenhäuser'), ('sn', 'Sonstige Einrichtung')], max_length=100, verbose_name='Einrichtungsart')),
                ('einrichtungs_id', models.CharField(blank=True, max_length=50, verbose_name='Einrichtungs-Id')),
                ('strasse', models.CharField(blank=True, max_length=100, verbose_name='Straße')),
                ('plz', models.CharField(blank=True, max_length=5, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('versorgungsumlage', models.DecimalField(choices=[(Decimal('0.00'), 'keine'), (Decimal('0.40'), '40 %'), (Decimal('0.68'), '68 %')], decimal_places=2, default=Decimal('0.40'), max_digits=4, verbose_name='Versorgungsumlage')),
                ('aktiv', models.BooleanField(default=True)),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('ansprechpartner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einrichtungen', to='ansprechpartner.ansprechpartner')),
                ('traeger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einrichtungen', to='traeger.traeger')),
            ],
            options={
                'verbose_name': 'Einrichtung',
                'verbose_name_plural': 'Einrichtungen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stelle',
            name='einrichtung',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stellen', to='traeger.einrichtung'),
            preserve_default=False,
        ),
    ]
