# Generated by Django 6.0.7 on 2026-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansprechpartner', '0001_initial'),
        ('traeger', '0007_remove_stelle_traeger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einrichtung',
            name='einrichtungs_id',
            field=models.CharField(db_index=True, help_text='Fachlicher Schlüssel für Import/Export – Sammel-Ids sind erlaubt, Id + Name müssen zusammen eindeutig sein', max_length=50, verbose_name='Einrichtungs-Id'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='stellen_id',
            field=models.CharField(db_index=True, help_text='Fachlicher Schlüssel für Import/Export – Sammel-Ids sind erlaubt, Id + Name müssen zusammen eindeutig sein', max_length=50, verbose_name='Stellen-Id'),
        ),
        migrations.AlterField(
            model_name='traeger',
            name='traeger_id',
            field=models.CharField(db_index=True, help_text='Fachlicher Schlüssel für Import/Export – muss eindeutig sein', max_length=50, verbose_name='Träger-Id'),
        ),
        migrations.AddConstraint(
            model_name='einrichtung',
            constraint=models.UniqueConstraint(condition=models.Q(('einrichtungs_id', ''), _negated=True), fields=('einrichtungs_id', 'name'), name='einrichtung_id_name_eindeutig'),
        ),
        migrations.AddConstraint(
            model_name='stelle',
            constraint=models.UniqueConstraint(condition=models.Q(('stellen_id', ''), _negated=True), fields=('stellen_id', 'name'), name='stelle_id_name_eindeutig'),
        ),
        migrations.AddConstraint(
            model_name='traeger',
            constraint=models.UniqueConstraint(condition=models.Q(('traeger_id', ''), _negated=True), fields=('traeger_id',), name='traeger_traeger_id_eindeutig'),
        ),
    ]
