# Generated by Django 6.0 on 2026-01-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lebensweisheit',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='berufsgruppe',
            field=models.CharField(choices=[('di', 'Diakon*innen'), ('pf', 'Pfarrer*innen'), ('tp', 'Pädergog*innen'), ('rel', 'Religionspädergog*innen'), ('mu', 'Kirchenmusiker*innen')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stellenkuerzel',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
