# Generated by Django 6.0 on 2026-01-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_userprofile_lebensweisheit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dienst_beendet',
            field=models.DateField(blank=True, null=True),
        ),
    ]
