# Generated by Django 6.0 on 2026-01-18 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0006_alter_mitarbeiter_options_and_more'),
        ('traeger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Einsatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.DateField()),
                ('ende', models.DateField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('bemerkung', models.TextField(blank=True)),
                ('angelegt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('angelegt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='angelegte_stelle_mitarbeiter', to=settings.AUTH_USER_MODEL)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.mitarbeiter')),
                ('stelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einsaetze', to='traeger.stelle')),
            ],
        ),
    ]
