# Generated by Django 6.0 on 2026-01-21 19:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einsatz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatz',
            name='umfang',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
    ]
