# Generated by Django 6.0 on 2026-01-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einsatz', '0002_einsatz_umfang'),
        ('personal', '0006_alter_mitarbeiter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einsatz',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einsaetze', to='personal.mitarbeiter'),
        ),
    ]
