# Generated by Django 6.0 on 2026-01-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einsatz', '0003_alter_einsatz_mitarbeiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatz',
            name='abrechnung',
            field=models.BooleanField(default=False, verbose_name='Abrechnung über LKA'),
        ),
    ]
