# Generated by Django 6.0 on 2026-01-16 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('personalnummer', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Personalnummer')),
                ('geschlecht', models.CharField(choices=[('w', 'weiblich'), ('m', 'männlich'), ('d', 'divers')], default='m', max_length=5, verbose_name='Geschlecht')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=100, verbose_name='Nachname')),
                ('geburtsdatum', models.DateField(verbose_name='Geburtsdatum')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-Mail')),
                ('telefon_privat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Privatnummer')),
                ('telefon_dienst', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dienstnummer')),
                ('strasse', models.CharField(blank=True, max_length=50, null=True, verbose_name='Straße')),
                ('ort', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ort')),
                ('plz', models.CharField(blank=True, max_length=5, null=True, verbose_name='PLZ')),
                ('dienststand', models.CharField(choices=[('diakon', 'Diakon'), ('pfarrer', 'Pfarrer'), ('relpad', 'Religionspädagoge'), ('sozpad', 'Sozialpädagoge'), ('kimu', 'Kirchenmusiker')], default='diakon', max_length=100, verbose_name='Dienststand')),
                ('status_besoldung', models.CharField(choices=[('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10'), ('A11', 'A11'), ('A12', 'A12'), ('A13', 'A13'), ('A14', 'A14'), ('A15', 'A15')], max_length=10, verbose_name='Besoldungsgruppe')),
                ('status_stufe', models.PositiveSmallIntegerField(verbose_name='Besoldungsstufe')),
                ('familienstand', models.CharField(choices=[('ledig', 'Ledig'), ('verheiratet', 'Verheiratet'), ('geschieden', 'Geschieden'), ('verwitwet', 'Verwitwet'), ('partnerschaft', 'Eingetragene Partnerschaft')], max_length=30)),
                ('kinder', models.PositiveSmallIntegerField(default=0)),
                ('kindergeldberechtigt', models.BooleanField(default=False)),
                ('anspruch_voll', models.BooleanField(default=False, verbose_name='Voller OFZ-Anspruch')),
                ('aktiv', models.BooleanField(default=True)),
                ('bemerkung', models.TextField(blank=True)),
                ('angelegt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('angelegt_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitarbeiters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nachname', 'vorname'],
            },
        ),
    ]
