# Generated by Django 6.0 on 2026-01-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='anstellungs_status',
            field=models.CharField(choices=[('pr', 'privatrechtlich'), ('oer', 'öffentlich-rechtlich')], default='oer', max_length=100, verbose_name='Dienststand'),
        ),
    ]
