# Generated by Django 6.0 on 2026-01-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_mitarbeiter_anstellungs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitarbeiter',
            name='anstellungs_status',
            field=models.CharField(choices=[('oer', 'öffentlich-rechtlich'), ('pr', 'privatrechtlich')], default='oer', max_length=100, verbose_name='Dienststand'),
        ),
    ]
