# Generated by Django 6.0 on 2026-01-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_mitarbeiter_anstellungs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitarbeiter',
            name='anstellungs_status',
            field=models.CharField(choices=[('pr', 'privatrechtlich'), ('oer', 'öffentlich-rechtlich')], default='oer', max_length=100, verbose_name='Dienststand'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='ort',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Ort'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='plz',
            field=models.CharField(blank=True, default=1, max_length=5, verbose_name='PLZ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='status_stufe',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Besoldungsstufe'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='strasse',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Straße'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='telefon_dienst',
            field=models.CharField(blank=True, default=1, max_length=20, verbose_name='Telefon Dienstlich'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='telefon_privat',
            field=models.CharField(blank=True, default=1, max_length=20, verbose_name='Telefon Privat'),
            preserve_default=False,
        ),
    ]
