# Generated by Django 6.0 on 2026-01-18 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_alter_mitarbeiter_anstellungs_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitarbeiter',
            options={'ordering': ['nachname', 'vorname'], 'verbose_name': 'Mitarbeiter', 'verbose_name_plural': 'Mitarbeiter'},
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='angelegt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='angelegte_mitarbeiter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='familienstand',
            field=models.CharField(choices=[('ledig', 'Ledig'), ('verheiratet', 'Verheiratet'), ('geschieden', 'Geschieden'), ('verwitwet', 'Verwitwet'), ('partnerschaft', 'Eingetragene Partnerschaft')], default='ledig', max_length=30),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='geschlecht',
            field=models.CharField(choices=[('w', 'weiblich'), ('m', 'männlich'), ('d', 'divers')], default='m', max_length=1, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='nachname',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='ort',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='personalnummer',
            field=models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, verbose_name='Personalnummer'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='status_besoldung',
            field=models.CharField(choices=[('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10'), ('A11', 'A11'), ('A12', 'A12'), ('A13', 'A13'), ('A14', 'A14'), ('A15', 'A15')], default='A10', max_length=10, verbose_name='Besoldungsgruppe'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='strasse',
            field=models.CharField(blank=True, max_length=150, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='telefon_dienst',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon Dienstlich'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='telefon_privat',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon Privat'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='vorname',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Vorname'),
        ),
    ]
