# Generated by Django 6.0 on 2026-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_mitarbeiter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='beihilfe_art',
            field=models.CharField(choices=[('privat_830', 'Privat versichert – Pauschale altersabhängig (Tarif 830)'), ('privat_814', 'Privat versichert – Pauschalbeitrag (Tarif 814)'), ('gesetzlich', 'Freiwillig gesetzlich – KV-Zuschuss + Beihilfeanspruch'), ('keine', 'Keine')], default='keine', max_length=20, verbose_name='Beihilfe-Art'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='beihilfe_kinder_monat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nur freiwillig gesetzlich Versicherte: monatlicher Beihilfeanspruch für Kinder laut Beihilfestelle', max_digits=8, null=True, verbose_name='Beihilfeanspruch Kinder mtl.'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='beihilfe_monat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nur freiwillig gesetzlich Versicherte: monatlicher Beihilfeanspruch laut Beihilfestelle', max_digits=8, null=True, verbose_name='Beihilfeanspruch mtl.'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='ehegatte_beihilfe',
            field=models.BooleanField(default=False, help_text='Ehegatte ist in der Beihilfeablöseversicherung mitversichert', verbose_name='Ehegatte beihilfeversichert'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='kv_zuschuss_monat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nur freiwillig gesetzlich Versicherte: monatlicher Krankenversicherungszuschuss', max_digits=8, null=True, verbose_name='KV-Zuschuss mtl.'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='ortsklasse',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII')], help_text='Mietenstufe des Hauptwohnsitzes nach Wohngeldverordnung (BayBesG Art. 36)', max_length=3, verbose_name='Ortsklasse'),
        ),
    ]
