# Generated by Django 6.0 on 2026-01-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansprechpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geschlecht', models.CharField(choices=[('w', 'weiblich'), ('m', 'männlich'), ('d', 'divers')], default='m', max_length=1, verbose_name='Geschlecht')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer')),
                ('notiz', models.TextField(blank=True, verbose_name='Notiz')),
                ('aktiv', models.BooleanField(default=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ansprechpartner',
                'verbose_name_plural': 'Ansprechpartner',
                'ordering': ['nachname', 'vorname'],
                'unique_together': {('vorname', 'nachname', 'email')},
            },
        ),
    ]
